# Generated by Django 2.2.5 on 2019-11-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191129_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mysport1',
            field=models.CharField(default='Soccer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='mysport2',
            field=models.CharField(default='Basketball', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='myteam',
            field=models.CharField(default='Arsenal', max_length=100),
            preserve_default=False,
        ),
    ]
