# Generated by Django 2.2.5 on 2019-12-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191130_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(default='en', max_length=100),
            preserve_default=False,
        ),
    ]
