# Generated by Django 2.1.9 on 2019-11-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teams',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=100)),
                ('teamImage', models.ImageField(upload_to='team')),
            ],
        ),
    ]
